# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: h0x0er/harden-runner@agent-mitm
      - run: file /usr/local/bin/mitmdump
      - run: ls -lah /home/mitmproxyuser
      - run: cat /home/mitmproxyuser/interceptor.py
      - run: sudo -u mitmproxyuser -H sh -c '/usr/local/bin/mitmdump --mode transparent -s /home/mitmproxyuser/interceptor.py&'
      - run: curl https://google.com/django

      - run: cat "/tmp/mitm-logs"
      - run: cat "/tmp/blocked-paths"
     
