name: Bottlerocket

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Smoke Test
    strategy:
      fail-fast: false
      matrix:
        # for kernel tags: https://quay.io/repository/lvh-images/kind?tab=tags
        # currently used tags are take from: https://github.com/harden-runner-canary/little-vm-helper-images/pull/1#issuecomment-2580730230
        kernel: ["bottlerocket61102-20250112.172734-amd64"]
    timeout-minutes: 10
    steps:

      - name: Provision LVH VMs
        uses: harden-runner-canary/little-vm-helper@jatin/custom # v0.0.19
        with:
          test-name: tracer-test
          image-version: ${{ matrix.kernel }}
          host-mount: .
          install-dependencies: "true"
          cmd: |
            uname -a
            ls -lah /boot
            cat /boot/config*
