name: BottleRocket Kernel Kit
# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: docker build
        run: |
          docker build . -t kkit -f ./Dockerfile2
         
