name: Dev Stress Test

on:
  workflow_dispatch:

jobs:
  stress-test:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: h0x0er/harden-runner@dev-test
        with:
          egress-policy: audit
      - uses: actions/checkout@main
      - run: curl "https://api.github.com"
      - run: curl "localhost:9191/status" | jq
      - run: curl "localhost:9191/tls?lib=/usr/bin/ls"
      - run: curl "localhost:9191/tls?lib=/usr/bin/xyz"
      
      
      
      # - run: |
      #    wget "https://raw.githubusercontent.com/urbanadventurer/WhatWeb/master/plugin-development/alexa-top-1000.txt"
      #    for domain in `cat alexa-top-1000.txt`; do curl --connect-timeout 3 -XGET "https://$domain" || continue; done
    
