name: Env Access
on:
  workflow_dispatch

env:
  author: "h0x0er"
jobs:
  build:
    if: github.author == ${{ env.author }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
