# This is a basic workflow to help you get started with Actions

name: Docker Pull

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "Give some name"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: "${{inputs.name}}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
 
      - name: Harden Runner
        uses: h0x0er/harden-runner@test-issue789
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-telemetry: true

      - run: docker pull mcr.microsoft.com/dotnet/aspnet:7.0@sha256:debec27f5579ddee99c2fd5616ee18def873aa83ad68e7b563c222162099fda5
