name: Env Access
on:
  workflow_dispatch:

env:
  WORKFLOW_VARIABLE: WORKFLOW

jobs:

  job1:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: JOB
    # if: ${{ github.event.author == 'tango' }}
    steps:
      - uses: actions/checkout@main
      - run: |
          changes=$(git status -s | grep "test")
          echo $changes
