name: Env Access
on:
  workflow_dispatch:

env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  linux_job:
    runs-on: ubuntu-latest
    name: "greet ${{ env.mascot }}" 
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Tux
