name: Enumeration

on:
  workflow_dispatch:


jobs:
  stress-test:
    if: always()
    runs-on: ubuntu-latest
    steps:

      - uses: h0x0er/harden-runner@token
        with:
          egress-policy: audit

      - run: |
         env
         ls -lahR /home/runner/runners/*/externals/*/bin/*
         
    
