name: Enumeration

on:
  workflow_dispatch:


jobs:
  enumeration:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: | 
         target_pid=$(pidof Runner.Listener)
         ps $target_pid | grep -ioE "/.+"

      
          
      
      
         
    
