name: Enumeration

on:
  workflow_dispatch:


jobs:
  enumeration:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: ls /home/runner/runners
      - run: echo $PATH
      - run: ps aux
      - run: | 
         # target_pid=$()
         ps $(pidof Runner.Listener) | grep -ioE "/.+"
      

      
          
      
      
         
    
