name: Enumeration

on:
  workflow_dispatch:


jobs:
  enumeration:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: ps aux
      - run: | 
         target_pid=$(pidof Runner.Listener)
         cat /proc/$target_pid/cwd

      
          
      
      
         
    
