
name: Gist Call

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Harden Runner
        uses: step-security/harden-runner@int
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Gist call
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/gists \
          -d '{"description":"Example of a gist","public":false,"files":{"README.md":{"content":"Hello World"}}}'
