
name: Harden_int

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wildcard:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: step-security/harden-runner@int 
        with:
          egress-policy: audit

          
      - run: curl "https://maps.google.com"
      - run: curl "https://play.google.com"
