name: INT B

on:
  workflow_dispatch:

jobs:
  enumeration:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: h0x0er/harden-runner@int #debug2
        with:
         egress-policy: block
         agent-env: int-pull
         tls-env: agent

      - run: curl https://youtube.com

      
          
      
      
         
    
