name: INT B

on:
  workflow_dispatch:

jobs:
  enumeration:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc #debug2
        with:
         egress-policy: audit
         disable-telemetry: true
         #agent-env: int
         #tls-env: agent

      - run: curl https://api.github.com/v2
      - run: sleep 180

      
          
      
      
         
    
