name: Mitm Docker Pull
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-docker-pull:
    name: mitm docker
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        disable-sudo: false
        egress-policy: audit
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - run: sudo docker pull alpine/curl



  mitm-docker-pull-block:
    name: mitm docker block
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          downloads.mitmproxy.org:443
          github.com:443
          int.api.stepsecurity.io:443
          production.cloudflare.docker.com:443
          registry-1.docker.io:443
        allowed-paths: >
          head:registry-1.docker.io:/v2/alpine/curl/manifests/5.5
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - run: sudo docker pull alpine/curl