name: Mitm MHardenRunner Test
on: 
  workflow_dispatch
jobs:
  block22:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@agent-mitm
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
        allowed-paths: >
          get:www.google.com:/
        agent-version: 0.0.57
        
    - uses: actions/checkout@v3

    - run: curl -X GET https://www.google.com

    - run: curl -X GET https://api.github.com

    - run: curl -X GET https://www.google.com/search

    - run: cat /tmp/mitm-logs
  block20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@agent-mitm
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
        allowed-paths: >
          get:www.google.com:/
        agent-version: 0.0.57
        
    - uses: actions/checkout@v3

    - run: curl -X GET https://www.google.com

    - run: curl -X GET https://api.github.com

    - run: curl -X GET https://www.google.com

    - run: cat /tmp/mitm-logs
  audit22:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@agent-mitm
      with:
        egress-policy: audit
        agent-version: 0.0.57
        
    - uses: actions/checkout@v3

    - run: curl -X GET https://www.google.com

    - run: curl -X GET https://api.github.com
    
    

    - run: curl -X GET https://www.google.com

    - run: cat /tmp/mitm-logs
  audit20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@agent-mitm
      with:
        egress-policy: audit
        agent-version: 0.0.57
        
    - uses: actions/checkout@v3

    - run: curl -X GET https://www.google.com

    - run: curl -X GET https://api.github.com

    - run: curl -X GET https://www.google.com

    - run: cat /tmp/mitm-logs
