name: Mitm Docker Pull
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-docker:
    name: mitm docker
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        disable-sudo: false
        egress-policy: audit
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - run: sudo docker pull alpine/curl

