name: Mitm Setup Java
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-setup-java:
    name: mitm setup java
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        egress-policy: audit

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17