name: Mitm Docker Build
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-docker:
    name: mitm docker
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        disable-sudo: false
        egress-policy: audit
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - run: cat /home/runner/.docker/config.json
    - run: cat /etc/docker/daemon.json

    - run: sudo mkdir -p /etc/docker/certs.d/mitmproxy/
    - run: sudo cp /home/mitmproxyuser/.mitmproxy/mitmproxy-ca-cert.pem /etc/docker/certs.d/mitmproxy/ca.crt
    - run: sudo service docker restart

    - run: sudo docker build -t testbuild .


  # docker-build-block:
  #   name: docker build block
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Harden Runner
  #     uses: h0x0er/harden-runner@mitm-int
  #     with:
  #       egress-policy: block
  #       allowed-endpoints: >
  #         auth.docker.io:443
  #         dl-cdn.alpinelinux.org:80
  #         downloads.mitmproxy.org:443
  #         files.pythonhosted.org:443
  #         github.com:443
  #         int.api.stepsecurity.io:443
  #         production.cloudflare.docker.com:443
  #         pypi.org:443
  #         pypi.python.org:443
  #         registry-1.docker.io:443
  #       allowed-paths: >
  #        head:registry-1.docker.io:/v2/library/alpine/manifests/3.5 
  #   - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
  #   - run: sudo docker build -t testbuild .


  # docker-build-block-job-fail:
  #   name: docker build block job fail
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Harden Runner
  #     uses: h0x0er/harden-runner@mitm-int
  #     with:
  #       egress-policy: block
  #       allowed-endpoints: >
  #         auth.docker.io:443
  #         dl-cdn.alpinelinux.org:80
  #         downloads.mitmproxy.org:443
  #         files.pythonhosted.org:443
  #         github.com:443
  #         int.api.stepsecurity.io:443
  #         production.cloudflare.docker.com:443
  #         pypi.org:443
  #         pypi.python.org:443
  #         registry-1.docker.io:443
  #   - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
  #   - run: sudo docker build -t testbuild .

  # docker-build-block-fail:
    # name: docker build block fail
    # runs-on: ubuntu-latest
    # steps:
    # - name: Harden Runner
    #   uses: h0x0er/harden-runner@mitm-int
    #   with:
    #     egress-policy: block
    #     allowed-endpoints: >
    #       auth.docker.io:443
    #       dl-cdn.alpinelinux.org:80
    #       downloads.mitmproxy.org:443
    #       files.pythonhosted.org:443
    #       github.com:443
    #       int.api.stepsecurity.io:443
    #       production.cloudflare.docker.com:443
    #       pypi.org:443
    #       pypi.python.org:443
    #       registry-1.docker.io:443
    #     allowed-paths: >
    #      head:registry-1.docker.io:/v2/library/alpine/manifests/3.4 

    # - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    # - run: sudo docker build -t testbuild .