name: Mitm Setup Java
on:
  workflow_dispatch:

permissions:
  contents: read


# env:
  # SSL_CERT_DIR: "/home/mitmproxyuser/.mitmproxy/"
      
jobs:
  mitm-setup-java:
    name: mitm setup java
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        egress-policy: audit
    - run: ps aux
    - run: dig dns.google
    - run: dig cloudflare-dns.com
    - run: dig int.api.stepsecurity.io
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
