name: Mitm Setup Java
on:
  workflow_dispatch:

permissions:
  contents: read


# env:
  # SSL_CERT_DIR: "/home/mitmproxyuser/.mitmproxy/"
      
jobs:
  mitm-setup-java:
    name: mitm setup java
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        egress-policy: audit

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: 'zulu'
    #     java-version: 17
    - run: ls -lah /home/agent/.mitmproxy
    - run: ls /usr/local/bin
    - run: curl https://cdn.azul.com/zulu/bin/zulu17.44.17-ca-crac-jdk17.0.8-linux_x64.tar.gz 