name: Recurring INT tests
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  int-tests:
    name: int tests
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@agent-mitm
      with:
        disable-sudo: false
        egress-policy: audit
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
        allowed-paths: >
          get:www.google.com:/
        agent-version: 0.0.57

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary-long: true
