name: Mitm Docker 
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-docker:
    name: mitm docker
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        disable-sudo: false
        egress-policy: audit
        
    - run: cat ~/.docker/config.json
    - run: sudo netstat -ltp
    - run: sudo docker pull alpine/curl
    - run: sudo docker ps
    - run: sudo docker run alpine/curl https://google.com
