name: Outputs
on:
  workflow_dispatch:


env:
  APPROVAL_HOOK_ENV: "prod"

jobs:
  capture_outputs:
    runs-on: ubuntu-latest
    steps:


     - name: Generate Labels
       id: labels
       run: |
        if [[ $APPROVAL_HOOK_ENV == "prod" ]]; then
           echo "label1=first_label-prod" >> $GITHUB_OUTPUT
        else
          echo "label1=first_label-int" $GITHUB_OUTPUT
        fi

     - run: echo "${{ steps.labels.outputs.label1 }}"
