name: Init Envs
on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  initialize-envs:
    name: init envs
    runs-on: ubuntu-latest
    steps:

    - run: "cloud_envs=('aws' 'gke');echo ${cloud_envs[RANDOM%2]}"
    - run: "deployment_methods=('helm' 'argo');echo ${deployment_methods[RANDOM%2]}"
    - run: "release_branches=('main' 'int');echo ${release_branches[RANDOM%2]}"

 