name: Stress Test

on:
  workflow_dispatch:


jobs:
  stress-test:
    if: always()
    runs-on: ubuntu-latest
    steps:
         
      - uses: h0x0er/harden-runner@token
        with:
          egress-policy: audit

      - run: |
         domains=""
         for x in {1..500}; do curl -XPOST "https://api.github.com/$x"&; done
    
