name: SystemStat

on:
  workflow_dispatch:

jobs:
  system-stat:
    if: always()
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: cat /proc/stat
      - run: cat /proc/meminfo

      - run: ls -lahR /opt/hostedtoolcache/node/*/*/bin
          
      
      
         
    
