name: View Certs
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-int-audit-test:
    name: View Certs
    runs-on: ubuntu-latest
    steps:
        
    - run: sudo ls /etc/ssl/certs/
    - run: sudo cat /etc/ssl/certs/Amazon_Root_CA_1.pem