name: View Certs
on:
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  mitm-int-audit-test:
    name: View Certs
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: h0x0er/harden-runner@mitm-int
      with:
        disable-sudo: false
        egress-policy: audit  

    - run: sudo cat /etc/ca-certificates.conf
    - run: sudo cat /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt